### ISSUE TITLE
Menu Design

### ISSUE THREAD

**Issue by dragon29708** [dragon29708/crawl-proj#9]
Given that the main options menu is selected
When I press the options button, an options menu pops up 
I am presented with well-formatted categories and intuitive user controls

**Comment by kevinaoliver** [comment]
Uploaded menu design. I turned the “Most Used” button mentioned in the User Stories document into 4 separate ones for now. Should be easy to change if needed. ![B1395855-04F1-4F2E-B923-82787E602F1E](https://user-images.githubusercontent.com/51456465/113316702-a2fecc80-92dc-11eb-8c6d-12e3168b8ad6.png)
